
#Auhtor: Kevin Jenkins and ChatGPT
#This code uses the output files generated by IPA_Analysis_code_part_I.py.
#This code produces a text file that lists the highest IPA_avg among the different batch sizes for each pruning percentage and pruning layer combo. 
#This code produces two  text files that are located within the directory for each type of pruning layer:
#  -One file lists the highest IPA_avg and its STD among the different batch sizes for each pruning percentage and pruning layer combo for plotting.
#  -The second file lists the IPA-avg and STD for each BS for each P%.


import os
import re

# Function to parse IPA_avg_std.txt files
def parse_ipa_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        # Check if the file has at least one line
        if lines:
            # Search for the line that contains the relevant information
            for line in reversed(lines):
                match = re.search(r'Avg IPA for [^\s]+: (\d+\.\d+), StdDev IPA: (\d+\.\d+)', line.strip())
                if match:
                    avg_ipa = float(match.group(1))
                    std_dev = float(match.group(2))
                    return avg_ipa, std_dev
    # If parsing fails, return None
    return None, None

# Function to process directories and generate output
def process_directories():
    root_dir = os.getcwd()
    print("Root directory:", root_dir)
    # Prune layers directories
    prune_layers = ["prune_layers_ALL", "prune_layers_CONV", "prune_layers_FHL", "prune_layers_FHL+SHL", "prune_layers_SHL"]

    for prune_layer in prune_layers:
        output_file = os.path.join(root_dir, prune_layer, f"{prune_layer}_output.txt")
        output_file_highest = os.path.join(root_dir, prune_layer, f"{prune_layer}_output_highest.txt")  # New output file for highest IPA values
        print("Output file:", output_file)

        with open(output_file, 'w') as output, open(output_file_highest, 'w') as output_highest:
            output.write("{:<10} {:<20} {:<20} {:<20}\n".format("P%", "IPA_Average", "STD", "BS"))
            output_highest.write("{:<10} {:<20} {:<20} {:<20}\n".format("P%", "IPA_Highest", "STD", "BS"))

            for percentage in [i / 100 for i in range(0, 110, 10)]:
                percentage_dir = f"p-percentage_{percentage}"
                highest_ipa = -1.0  # Initialize highest IPA value
                highest_batch_size = None

                for batch_size in [64,1024]:
                    batch_size_dir = os.path.join(root_dir, prune_layer, percentage_dir, f"batch_size_{batch_size}")
                    ipa_file_path = os.path.join(batch_size_dir, "IPA_avg_std.txt")
                    print("IPA file path:", ipa_file_path)

                    if os.path.exists(ipa_file_path):
                        avg_ipa, std_dev = parse_ipa_file(ipa_file_path)
                        if avg_ipa is not None and std_dev is not None:
                            output.write("{:<10} {:<20} {:<20} {:<20}\n".format(percentage, "{:.9f}".format(avg_ipa), "{:.9f}".format(std_dev), batch_size))

                            # Update highest IPA value and corresponding batch size if needed
                            if avg_ipa > highest_ipa:
                                highest_ipa = avg_ipa
                                highest_batch_size = batch_size
                        else:
                            print("Error parsing file:", ipa_file_path)
                    else:
                        print("File not found:", ipa_file_path)

                # Write only the entry with the highest IPA value to the output file for highest values

                # Write only if a valid highest IPA value was found: to navigate through empty IPA_avg_std.txt for p-1.0
                if highest_ipa >= 0 and highest_batch_size is not None:
                    output_highest.write("{:<10} {:<20} {:<20} {:<20}\n".format(percentage,"{:.9f}".format(highest_ipa),"{:.9f}".format(std_dev),highest_batch_size))
                #else: # if need to put value for p-100 to be NA
                    #output_highest.write("{:<10} {:<20} {:<20} {:<20}\n".format(percentage,"N/A","N/A","N/A"))


# Main function
def main():
    process_directories()

if __name__ == "__main__":
    main()

